# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Release
on:
  release:
    types:
      -created

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Send webhook for deploy
        run: "curl --silent --show-error --fail -X POST ${{ secrets.DEPLOYMENT_SERVER }}/release -H 'Authorization: ${{ secrets.DEPLOYMENT_TOKEN }}'"
